### ISSUE TITLE
0.0.3 enhancements checklist

### ISSUE THREAD

**Issue by zsherman** [timberio/react-facet-filter#4]
- [ ] Custom version of `<List>` component (current one does not handle selection/clicking well)
- [ ] Clear all filters 'x' button on right side
- [ ] Properly handle duplicate filters (can be toggled with the noRepeat prop)
- [ ] Ignore quotes inside options when filtering results [(example)](https://www.dropbox.com/s/1hjms8nxoppqg8d/Screenshot%202016-08-24%2013.45.30.png?dl=0)
- [ ] debounce autocomplete calls
- [ ] Allow custom filter function to choose which matches to highlight
- [ ] Properly handle cmd + left or right
- [ ] Write some basic tests
- [ ] Cursor jumps to end of input when updating a category/option, should move to the end of the option you just selected
- [ ] Options loading state jumps to bottom before attached to input
- [ ] Handle prop that toggles full width autocomplete results
- [ ] Support `>/=/<` expressions
- [ ] Holding down arrow should scroll options
- [ ] Add phantom suggestion on hover
  ![screen_shot_2015-07-01_at_9 42 40_am](https://cloud.githubusercontent.com/assets/1152279/17954780/49e7612a-6a4b-11e6-98bf-d0e87ca6717c.png)
